apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eco-matcher-agent
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    spec:
      serviceAccountName: 610755018887-compute@developer.gserviceaccount.com
      containers:
        - image: BACKEND_IMAGE  # <--- Cloud Build will replace this
          name: backend
          resources:
            limits: { cpu: "1", memory: "512Mi" }
          ports:
            - containerPort: 8000
        - image: FRONTEND_IMAGE # <--- Cloud Build will replace this
          name: frontend
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_URL
              value: "http://localhost:8000/chat"